### ISSUE TITLE
Composer missing

### ISSUE THREAD

**Issue by peterkokot** [devtosystems/ts-framework#6]
If I may suggest adding composer.json as well. Check here for more information:
https://getcomposer.org/
Regards.

**Comment by peterkokot** [comment]
I was just going through my opened issues list and since this ticket is quite old I'll close it. Though Composer would be a good feature in some future update. Cheers. :)

**Comment by devtosystems** [comment]
Oh, thanks @peterkokot for contributon! :+1:
